name: 'Backend CI/CD 🚀'
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker_operations:
    name: 'Docker Build and Push🐳'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        if: startsWith(github.ref, 'refs/tags/') != true && success()
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${GITHUB_SHA::7} .
      - name: Push Docker image
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${GITHUB_REF/refs\/tags\//} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${GITHUB_REF/refs\/tags\//}
